# Import all the requirements

In [59]:
from bs4 import BeautifulSoup as bs
import requests
import re
import pandas as pd

# Make the user-agent

In [60]:
header = {
    'user-agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
}

# Make function of browse and find the data

In [61]:
def browse_and_find(keyword):

    keyword = keyword.lower().replace(" ", "-")
    # browse with keyword 
    url = f"https://www.jobstreet.co.id/id/{keyword}-jobs"
    req = requests.get(url, headers = header)
    sup = bs(req.text, 'html.parser')

    title =  [i.text for i in sup.find_all('div', 'z1s6m00 l3gun70 l3gun74 l3gun72')]
    region = [i.text for i in sup.find_all('span', 'z1s6m00 _1hbhsw64y y44q7i0 y44q7i3 y44q7i21 y44q7ih') if re.search(r'[0-9]+', i.text) == None]
    company = [i.text for i in sup.find_all('span', 'z1s6m00 bev08l1 _1hbhsw64y _1hbhsw60 _1hbhsw6r') if i.text not in region][5:35]
    category = [keyword]*len(title)

    data = {'title':title,
            'region':region,
            'company':company,
            'category':category}
    
    return data

# you can process the data manually without function like this

In [62]:
data1 = browse_and_find('software engineer')
data2 = browse_and_find('data science')
data3 = browse_and_find('ui ux design')

In [63]:


data1 = pd.DataFrame(data1)
data2 = pd.DataFrame(data2)
data3 = pd.DataFrame(data3)

data = pd.concat([data1, data2, data3], ignore_index=True)
data

,title,region,company,category
0,Remote Delphi Software Engineer,Jawa Barat,PT Tetra Indo Teknologi,software-engineer
1,Software Engineer,Jakarta Raya,PT. Wide Technologies Indonesia,software-engineer
2,Outsystem Developer (Junior & Middle),Jakarta Raya,PT.JAGOGO ANALISA GEMILANG,software-engineer
3,.Net Developer,Jakarta Pusat,Agung Logistics,software-engineer
4,RnD Senior Software Engineer,"Bandung, Salatiga, Semarang",PT Formulatrix Indonesia,software-engineer
...,...,...,...,...
85,Industrial Product Designer - R&D,Bogor,LEGANO,ui-ux-design
86,Design Lead,Banten,Sekolah Pelita Harapan,ui-ux-design
87,UI UX Designer,Badung,Kesato.Co,ui-ux-design
88,Sr UX Designer,Jakarta Raya,PT. Elabram Systems,ui-ux-design
89,React JS Programmer,Jakarta Raya,PT Nutech Integrasi,ui-ux-design

# Or, you can make a function like this to save more energy

In [64]:
def frame_all_data(keywords):

    data_list = []
    for i in keywords:
        data = browse_and_find(i)
        data_list.append(pd.DataFrame(data))

    return pd.concat([i for i in data_list], ignore_index=True)

In [65]:
data = frame_all_data(['software engineer', 'data science', 'ui ux design'])
data

,title,region,company,category
0,Remote Delphi Software Engineer,Jawa Barat,PT Tetra Indo Teknologi,software-engineer
1,Software Engineer,Jakarta Raya,PT. Wide Technologies Indonesia,software-engineer
2,Outsystem Developer (Junior & Middle),Jakarta Raya,PT.JAGOGO ANALISA GEMILANG,software-engineer
3,RnD Senior Software Engineer,"Bandung, Salatiga, Semarang",PT Formulatrix Indonesia,software-engineer
4,.Net Developer,Jakarta Pusat,Agung Logistics,software-engineer
...,...,...,...,...
85,Product designer,Tangerang,PT Shangyang Technology Indonesia,ui-ux-design
86,Design Lead,Banten,Sekolah Pelita Harapan,ui-ux-design
87,UI /UX,Jawa Barat,PT. Jago Talenta Indonesia,ui-ux-design
88,Packaging Designer,Bandung,PT Timur Tengah Indonesia,ui-ux-design
89,Regional UI/UX Designer -Indonesia,Jakarta Raya,LAZADA.CO.ID,ui-ux-design

# The results are the same, now make the csv file

In [68]:
data.to_csv('data.csv', index=False)